export const indianAirports = [
  { city: "Delhi", code: "DEL" },
  { city: "Mumbai", code: "BOM" },
  { city: "Bengaluru", code: "BLR" },
  { city: "Chennai", code: "MAA" },
  { city: "Kolkata", code: "CCU" },
  { city: "Hyderabad", code: "HYD" },
  { city: "Pune", code: "PNQ" },
  { city: "Ahmedabad", code: "AMD" },
  { city: "Jaipur", code: "JAI" },
  { city: "Goa", code: "GOI" },
  { city: "Kochi", code: "COK" },
  { city: "Lucknow", code: "LKO" },
  { city: "Thiruvananthapuram", code: "TRV" },
  { city: "Guwahati", code: "GAU" },
  { city: "Chandigarh", code: "IXC" },
  { city: "Bhubaneswar", code: "BBI" },
  { city: "Coimbatore", code: "CJB" },
  { city: "Indore", code: "IDR" },
  { city: "Nagpur", code: "NAG" },
  { city: "Varanasi", code: "VNS" },
];
