"""Initial migration

Revision ID: 2e9051def645
Revises: 
Create Date: 2025-02-26 18:50:27.618814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e9051def645'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airplanes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('passenger_capacity', sa.Integer(), nullable=False),
    sa.Column('crew_capacity', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('airline', sa.String(length=100), nullable=False),
    sa.Column('image_data', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authority',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('reg_no', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reg_no'),
    sa.UniqueConstraint('username')
    )
    op.create_table('crew',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_number'),
    sa.UniqueConstraint('license_number')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('contact_number', sa.String(length=50), nullable=False),
    sa.Column('dob', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.Column('nationality', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('flights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('from_code', sa.String(length=100), nullable=False),
    sa.Column('from_city', sa.String(length=100), nullable=False),
    sa.Column('from_time', sa.Time(), nullable=False),
    sa.Column('to_code', sa.String(length=100), nullable=False),
    sa.Column('to_city', sa.String(length=100), nullable=False),
    sa.Column('to_time', sa.Time(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('booked_seats', sa.Integer(), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('airplane_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['airplane_id'], ['airplanes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.DateTime(), nullable=True),
    sa.Column('seat_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight_crew',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('crew_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['crew_id'], ['crew.id'], ),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight_crew')
    op.drop_table('bookings')
    op.drop_table('flights')
    op.drop_table('users')
    op.drop_table('crew')
    op.drop_table('authority')
    op.drop_table('airplanes')
    # ### end Alembic commands ###
